Update index.js
Added check if body is set. Before the fix, I had the following for some requests:
```
error: TypeError: Object.keys called on non-object
  at Function.keys (native)
  at ServerResponse.res.end (/Users/mdarveau/perso/workspace/maligue/node_modules/express-winston/index.js:231:51)
  at ServerResponse.res.send (/Users/mdarveau/perso/workspace/maligue/node_modules/sails/node_modules/express/lib/response.js:153:8)
  at ServerResponse.res.json (/Users/mdarveau/perso/workspace/maligue/node_modules/sails/node_modules/express/lib/response.js:195:15)
```

Note that this only triggers if you have something in `bodyBlacklist` and nothing in `bodyWhitelist`.